### ISSUE TITLE
Tutorial source

### ISSUE THREAD

**Issue by luca-saggese** [Pagedraw/pagedraw#20]
hello,
first of all thanks for sharing such a beatiful piece of code, i'm trying to build an online editor for expo app.
I've successfully run the app in  the browser following the advices in a previous issue (for who is interested can find the code in my fork) but i would like to build something similar to your tutorial, with the editor attached.
any chance you would share the tutorial source?

Kind regards
Luca

**Comment by luca-saggese** [comment]
ok found out, is staticblitz linked and to load it i should change the route to blitz

**Comment by marcusellison** [comment]
Hi @luca-saggese ,

I've built a non-trivial application using pagedraw. I'm happy to chat about it. I'm also curious about learning more about what you're building for expo app and how it integrates with expo ecosystem. Feel free to message me: marcus@venturemark.co
