### ISSUE TITLE
Using Figma with desktop app

### ISSUE THREAD

**Issue by gautamchitnis** [Pagedraw/pagedraw#7]
Can someone help me out with the flow for using Figma designs with the desktop app?

I found a link describing how to use figma with website version over at: https://medium.com/pagedraw/pagedraw-figma-integration-5f99090ec1d4

Not sure how to use this on desktop version.

**Comment by marcusellison** [comment]
I don't think this feature is currently active.

When I used the web version over the summer I found it faster to build or recreate designs in pagedraw rather than importing from Figma since there were many errors in translating.
